import Head from 'next/head'
import Header from '../components/Header'
import {Nav} from '../components/Nav'
import  {Result} from '../components/Result'
import request from '../utils/request';
 




export default function Home(props) {
  console.log(props)
  return (
    <div>
      <Head>
        <title>Hulu -By Sagar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* Header  */}

      <Header />


      {/* Nav */}
       
       <Nav />


       
        

      {/* Result */}


   {/* <Result result={Result} /> */}
  

    </div>
  );
}


// export async function getServersideProps(context){
//   const genre =context.query.genre;

//   const request=await fetch(`https://api.themoviedb.org/3$
//   {request[genre]?.url ||request.fetchTrading.url
//   }`
//   ).then(res => res.json());

//   return{
//           props:{
//             result:request.result,
//           },
//   };


// }
